import { Todo } from '../types';

export const exportTodosToPDF = (todos: Todo[]) => {
  const win = window as any;
  const jsPDF = win.jspdf?.jsPDF || win.jsPDF || win.window?.jsPDF;
  
  if (!jsPDF) {
    console.log('Available:', Object.keys(win).filter(k => k.toLowerCase().includes('pdf')));
    alert('PDF library failed to load');
    return;
  }
  const doc = new jsPDF();
  
  // Use standard fonts only
  doc.setFont('helvetica');
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPos = margin;

  // Header
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(37, 181, 205);
  doc.text('Task List Report', margin, yPos);
  yPos += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, margin, yPos);
  yPos += 15;

  // Statistics
  const completed = todos.filter(t => t.completed).length;
  const total = todos.length;
  const completionRate = total > 0 ? Math.round((completed / total) * 100) : 0;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Tasks: ${total} | Completed: ${completed} | Pending: ${total - completed} | Completion Rate: ${completionRate}%`, margin, yPos);
  yPos += 15;

  // Tasks
  todos.forEach((todo, index) => {
    if (yPos > pageHeight - 40) {
      doc.addPage();
      yPos = margin;
    }

    // Task title
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    const status = todo.completed ? '[X]' : '[ ]';
    doc.text(`${status} ${todo.title}`, margin, yPos);
    yPos += 7;

    // Task details
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    
    const details = [];
    if (todo.priority) details.push(`Priority: ${todo.priority.toUpperCase()}`);
    if (todo.category) details.push(`Category: ${todo.category}`);
    if (todo.estimatedTime) details.push(`Est. Time: ${todo.estimatedTime}m`);
    if (todo.tags && todo.tags.length > 0) details.push(`Tags: ${todo.tags.join(', ')}`);
    
    if (details.length > 0) {
      doc.text(details.join(' | '), margin + 5, yPos);
      yPos += 5;
    }

    // Progress bar
    if (todo.subtasks && todo.subtasks.length > 0) {
      const progress = todo.progress || 0;
      doc.setDrawColor(200, 200, 200);
      doc.rect(margin + 5, yPos, 50, 3);
      
      const progressColor = progress === 100 ? [22, 180, 126] : progress > 50 ? [37, 181, 205] : [240, 122, 118];
      doc.setFillColor(progressColor[0], progressColor[1], progressColor[2]);
      doc.rect(margin + 5, yPos, (50 * progress) / 100, 3, 'F');
      
      doc.setTextColor(100, 100, 100);
      doc.text(`${progress}%`, margin + 60, yPos + 2.5);
      yPos += 7;
    }

    // Notes
    if (todo.notes) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(80, 80, 80);
      const lines = doc.splitTextToSize(todo.notes, pageWidth - margin * 2 - 10);
      doc.text(lines, margin + 5, yPos);
      yPos += lines.length * 4;
    }

    // Subtasks
    if (todo.subtasks && todo.subtasks.length > 0) {
      yPos += 2;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(100, 100, 100);
      doc.text('Subtasks:', margin + 5, yPos);
      yPos += 5;

      todo.subtasks.forEach(subtask => {
        if (yPos > pageHeight - 20) {
          doc.addPage();
          yPos = margin;
        }
        const subStatus = subtask.completed ? '[X]' : '[ ]';
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(subtask.completed ? 100 : 0, subtask.completed ? 100 : 0, subtask.completed ? 100 : 0);
        doc.text(`  ${subStatus} ${subtask.title}`, margin + 10, yPos);
        yPos += 5;
      });
    }

    yPos += 8;
  });

  // Footer on last page
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by ConstructLM Task Manager', pageWidth / 2, pageHeight - 10, { align: 'center' });

  doc.save(`tasks-${new Date().toISOString().split('T')[0]}.pdf`);
};
